class ProjectPage extends CustomElm{
	constructor(){
		super();
		this.define(html`
			${new Surface(html`
				<h2>Overview</h2>
				${new ImageDisplay("img/flame_29.png")}
				<p>
					This program is able to render pixel art fire in real time on a single CPU thread. Unlike the vast majority of fire rendering methods currently available this program does not use Navier-Stokes equations or even require the use of a fluid simulator. It instead is based on simple cellular-automata like rules allowing for a much simpler system that is also able to run in real time without the use of the GPU.
				</p>
			`,"lg",false,true)}
			<div class="gap"></div>
			${new Surface(html`
				<h2>Inspiration</h2>
				<p>
					This was primarily inspired by <a href="https://softologyblog.wordpress.com/2019/04/11/physarum-simulations/">a project</a> done by Softology trying to simulate mold. Some of the simulations he had on display exhibited similar properties to a failed fluid simulation I had attempted to make earlier. That got me wondering if it would be possible to approximate fluid simulation using a similar approach. Fluid simulation is a problem that has been already solved by many people so I wanted to try a slightly different problem. Being a bit of a pyromaniac I have always wanted a way to simulate fire in real time. I got the idea from the game <a href="https://tomorrowcorporation.com/littleinferno">Little Inferno</a> and a few online demos I had seen such as <a href="https://www.escapemotions.com/experiments/fluid_fire_3/index.php">this one</a>.
				</p>
			`,"lg")}
			<div class="gap"></div>
			${new Surface(html`
				<h2>Results</h2>
				<p>
					Here are some samples of the flames generated by the program.
				</p>
				<h3>Animation</h3>
				${new VideoDisplay("video/fire.mp4")}
				<h3>Standard Flame</h3>
				${new ImageDisplay("img/flame_31.png")}
				<h3>Ring of Fire</h3>
				${new ImageDisplay("img/flame_32.png")}
				<h3>Small Flame</h3>
				${new ImageDisplay("img/flame_33.png")}
				${new ImageDisplay("img/flame_34.png")}
				<h3>"Cherry" Flame (color variant)</h3>
				${new ImageDisplay("img/flame_39.png")}
				${new ImageDisplay("img/flame_42.png")}
				${new ImageDisplay("img/flame_35.png")}
			`,"lg")}
			<p class="center">${new ButtonLink("back to top",()=>scrollToTop())}</p>
		`);
	}
}
defineElm(ProjectPage,scss`&{
	width: 100%;
	>.gap{
		height: 40px;
	}
	p.center{
		${theme.centerText}
	}
	.bold{
		font-weight: 700;
	}
	.projectLink{
		a{
			padding: 5px 10px;
			background-color: ${theme.color.greyStep(-2)};
			border-radius: 50px;
		}
	}
}`);

let title=bind("Fire Simulation");
let page=bind(null);
page.data=bind({
	content: new ProjectPage()
});