class ProjectPage extends CustomElm{
	constructor(){
		super();
		this.define(html`
			${new Surface(html`
				<h2>Overview</h2>
				<p class="center bold projectLink"><a href="https://github.com/AdrianMargel/simple-texture-generator">Github</a></p>
				${new ImageDisplay("img/tilesGen4.png")}
				<p>
					This program procedurally generates pixel art damaged sandstone tiles. This was mostly created as a test to see if concepts from <a href="https://en.wikipedia.org/wiki/Cellular_automaton">cellular automata</a> could be used in a more practical environment such as procedural generation. The tiles are generated by running a custom cellular automaton on randomly generated white noise. The results of the cellar automaton are then used as a depth variable for each pixel. Simple lighting effects are then applied to better show the generated texture.
				</p>
			`,"lg",false,true)}
			<div class="gap"></div>
			${new Surface(html`
				<h2>Inspiration</h2>
				<p>
					This project was inspired by past work I had done with cellular automata and a few projects I came across online involving procedural generation of pixel art tiles based on more conventional approaches. I was inspired to try using a cellular automata as the base for procedurally generated tiles.
				</p>
			`,"lg")}
			<div class="gap"></div>
			${new Surface(html`
				<h2>Results</h2>
				<p class="center">
					Below are a few tile sets generated with different settings.
				</p>
				${new ImageDisplay("img/tilesGen.png")}
				${new ImageDisplay("img/tilesGen2.png")}
				${new ImageDisplay("img/tilesGen3.png")}
			`,"lg")}
			<p class="center">${new ButtonLink("back to top",()=>scrollToTop())}</p>
		`);
	}
}
defineElm(ProjectPage,scss`&{
	width: 100%;
	>.gap{
		height: 40px;
	}
	p.center{
		${theme.centerText}
	}
	.bold{
		font-weight: 700;
	}
	.projectLink{
		a{
			padding: 5px 10px;
			background-color: ${theme.color.greyStep(-2)};
			border-radius: 50px;
		}
	}
}`);

let title=bind("Simple Textures");
let page=bind(null);
page.data=bind({
	content: new ProjectPage()
});